export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import { CarritoProvider } from "@/carrito"
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CarritoProvider>
        <body>{children}</body>
      </CarritoProvider>
    </html>
  )
}
